### PR TITLE
Update theme.json with missing fields

### PR DESCRIPTION
**Pull request by stefenphelps**
Add a few of the missing theme fields that the HubSpot Asset marketplace requires.

### CODE REVIEW

**Comment by jasonnrosa** [comment]
Thanks for the update here @stefenphelps! I think the update makes sense to me. For reviewers that I tagged on this, would just be curious what your thoughts on a good example email might be?

**Comment by TanyaScales** [comment]
Hmmm... you could send to our team's alias email? content-assets@hubspot.com? Not sure what else could go there other than a more generic support email.

**Review by jasonnrosa — APPROVED** [review]

**Comment by TheWebTech** [comment]
I don't know how likely it may be, but it's possible folks will try emailing that address. 

Id say something like no-reply@hubspot.com but we dont want folks using noreply addresses in marketplace themes. 

We may be able to use developers@hubspot.com but that too is an email that folks cant expect to treat like a support email address.

**Comment by jasonnrosa** [comment]
@TheWebTech yeah I think that is a good call. I'd say let's go with the content-assets email address to start and if we find that it is an issue we can swap it over to a more obvious one like a `no-reply@hubspot.com` email address.

**Pull request merged**
