### PR TITLE
Convert global partials to use drag and drop 

### LINKED ISSUE #291: Add drag and drop support to global content
### Description

Customers have been experiencing pain when trying to edit global content. Adding drag and drop support to the global:
- Header 
- Header-no-navigation
- Footer

### Expected behavior

In an effort to keep customer expectations accurate, we should omit content that changes position/style based on device. I believe that the elements that we need to consider are:
- Language switcher
- Search
- Main menu

Rather than including all elements in a drag and drop area, we can add drag and drop areas above and below the header content.

All footer content can be included in a drag and drop area as it retains the position/style across browser width/ device type.

### PR DESCRIPTION
**Pull request by jasonnrosa**
**Types of change**

- [ ] Bug fix (change which fixes an issue)
- [ ] Enhancement (change which improves upon an existing feature)
- [X] New feature (change which adds new functionality)

**Description**

Adding drag and drop support in global partials (header, footer, and header no navigation). 

**Relevant links**

Fixes #291 

**Checklist**

- [X] I have read the [CONTRIBUTING](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/CONTRIBUTING.md) document.
- [X] My code follows the [style guide requirements](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/STYLEGUIDE.md).
- [X] I have thoroughly tested my change.

### CODE REVIEW

**Comment by jasonnrosa** [comment]
CC: @ckconant I did my best to try to keep things as close as possible to the original. There is one other thing we could still do. That being remove the padding on `footer-container` and move the padding to the dnd_section in the footer partial but I wasn't sure what we wanted to do there. One note on that is if we remove that style we'd no longer have a need for the `footer.css` file.

**Comment by ckconant** [comment]
@jasonnrosa this looks good!  As for the padding issue on the footer, I think that from a consistency standpoint you can move the `.footer__container` padding to `.dnd-section`. However, do you feel that it is best to use the vertical spacing theme setting (default of `80px`) on the footer? Adding padding will break the design, but may help developers by adding consistency across `.dnd-section` style. Or, you can keep the fancy style HubL override on the section (like you have on lines 11-14 of footer.html). The downside to this is approach is that it overrides the theme settings so any initial theme adjustments won't be taken in to account and could be confusing for customers.

Now to contradict myself - I think that we should we remove the padding from `.dnd-section` on the header dnd_areas as the padding is currently applied to each of the dnd_areas in the header causing (most likely) unintended vertical spacing. Instead, we should consider including the vertical padding on `.header` element so that it takes into account the entire header and not fragments of it.

**Review by TanyaScales — APPROVED** [review]
LGTM other than the conversation you two are having around padding and vertical rhythm in the header/footer areas

**Comment by jasonnrosa** [comment]
> Or, you can keep the fancy style HubL override on the section (like you have on lines 11-14 of footer.html).

I think this seems like the best approach to me in this particular case. The boilerplate footer is really simple and the normal section spacing would look a little awkward in my opinion if applied to both top and bottom. How would you feel if we applied the section spacing to the footer and then set an override on the footer bottom in the fancy style? This way the overall spacing still follows theme settings to some degree but the footer still looks relatively similar. 

> I think that we should we remove the padding from .dnd-section on the header dnd_areas as the padding is currently applied to each of the dnd_areas in the header causing (most likely) unintended vertical spacing.

Hmmm.. I don't have any classes of `dnd-section` in my header/footer for whatever reason ([example link](http://jrosa-102019231.hs-sitesqa.com/-temporary-slug-9ff49374-3420-4eb7-a482-0d92007a4496?hs_preview=ApQaeCrx-4420545295)). Should this be getting applied around every global dnd section by default?

**Comment by ckconant** [comment]
> How would you feel if we applied the section spacing to the footer and then set an override on the footer bottom in the fancy style? This way the overall spacing still follows theme settings to some degree but the footer still looks relatively similar.

Sounds like a good plan 👍 

> Should we just proceed with something like .header .dnd-section { padding: 0; } and let the user set the padding in fancy styles for the blank dnd_areas if desired?

That works for me.

**Comment by jasonnrosa** [comment]
Made a few updates to wrap up remaining issues: 
- Set header dnd-section default padding to 0
- Set footer padding to pull from the theme settings and removed the `footer.css` file as there was no longer anything in it
- Removed `footer.css` reference in `main.css` and added some comments in that file defining the structure a bit more (pulled from default themes).

**Comment by ckconant** [comment]
Thanks for making the updates @jasonnrosa! I just tested a [new page](https://cconant-101677409.hs-sitesqa.com/-temporary-slug-225b0087-71b6-4b5a-ba48-c622c444471d?hs_preview=xfxbvvyu-4432188042) and there's only one issue that I'm seeing. It looks like the footer typography color is using the selector `.footer *` which is causing issues text that uses a different background. For example, the button in the footer looks like a dark box by default.
I've added an example in the footer of the page above.

**Comment by jasonnrosa** [comment]
@ckconant good catch 👍 I updated the CSS selector for the footer font setting and adjusted it to target specific CSS selectors instead of using `*`.

**Review by ckconant — APPROVED** [review]

**Pull request merged**
