### PR TITLE
jodn222

### PR DESCRIPTION
**Pull request by ksh5a**
**Types of change**

- [ ] Bug fix (change which fixes an issue)
- [ ] Enhancement (change which improves upon an existing feature)
- [ ] New feature (change which adds new functionality)

**Description**

A clear and concise description of what the pull request is solving.

**Relevant links**

Example page:
GitHub issue:

**Checklist**

- [ ] I have read the [CONTRIBUTING](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/CONTRIBUTING.md) document.
- [ ] My code follows the [style guide requirements](https://github.com/HubSpot/cms-theme-boilerplate/blob/master/STYLEGUIDE.md).
- [ ] I have thoroughly tested my change.

**People to notify**

### CODE REVIEW

**Comment by ksh5a** [comment]
welcome

**Comment by ksh5a** [comment]
welcome

**Comment by jasonnrosa** [comment]
Hey @ksh5a 👋🏼 would you be able to provide more information about what your PR accomplishes and what problem it is solving for?

**Comment by jasonnrosa** [comment]
Going to close this one out as we haven't heard back

**Pull request closed without merging**
