### PR TITLE
Use header block to leverage an alternate LP header

### PR DESCRIPTION
**Pull request by gcorne**

### CODE REVIEW

**Comment by axellabs** [comment]
I see what you did here. I'm going to test this in a portal, I like this form of organization

**Comment by axellabs** [comment]
I don't think this will work. The header appears in the homepage, but the styles would have to be adjusted because the markup changes. The header doesn't appear at all in the landing page with this method.

**Comment by gcorne** [comment]
@axellabs can you give it a spin now? I didn't update the path to the partials when copying and pasting from `base.html`.

**Comment by axellabs** [comment]
Ah I see what the issue was. Okay, this looks good to me.

**Pull request merged**
